### ISSUE TITLE
Surface_Go_2 dump results

### ISSUE THREAD

**Issue by kbingham** [kitakar5525/surface-ipu3-cameras#10]
[result_Surface_Go_2_Surface_Go_2_1901@v1.0.md.txt](https://github.com/kitakar5525/surface-ipu3-cameras/files/5487817/result_Surface_Go_2_Surface_Go_2_1901%40v1.0.md.txt)

**Comment by kitakar5525** [comment]
Thanks! added as https://github.com/kitakar5525/surface-ipu3-cameras/commit/a3dd4143472ca0d5644fb20621f51fad7239cf46

**Comment by kitakar5525** [comment]
ahhh, I have messed up something
```
kern  :info  : [  409.852730] dump_intel_ipu_data: Found -1509336319 supported sensor(s)
kern  :info  : [  409.852731] dump_intel_ipu_data: Found 1 supported PMIC(s)
```
