### ISSUE TITLE
SP6 dump results

### ISSUE THREAD

**Issue by SamLukeYes** [kitakar5525/surface-ipu3-cameras#11]
[result_Surface_Pro_6_Surface_Pro_6_1796_Consumer@v1.0.log](https://github.com/kitakar5525/surface-ipu3-cameras/files/5488362/result_Surface_Pro_6_Surface_Pro_6_1796_Consumer%40v1.0.log)

**Comment by kitakar5525** [comment]
Thanks!!! added to results directory as https://github.com/kitakar5525/surface-ipu3-cameras/commit/077a66bfa4c90881623c085480791792e441e3a6
