### ISSUE TITLE
Result on Microsoft Surface Pro 7

### ISSUE THREAD

**Issue by buchwasa** [kitakar5525/surface-ipu3-cameras#12]
[result_Surface_Pro_7_Surface_Pro_7_1866@v1.0.log](https://github.com/kitakar5525/surface-ipu3-cameras/files/5488636/result_Surface_Pro_7_Surface_Pro_7_1866%40v1.0.log)

**Comment by kitakar5525** [comment]
Thanks!!! added to results directory as https://github.com/kitakar5525/surface-ipu3-cameras/commit/013fb2808c8f773bdc10afbf1c2e780d10640340

By the way, it seems that I made a mistake on counting devices for Debian-based distros:
```
kern  :info  : [  217.930451] dump_intel_ipu_data: Found -1664481439 supported sensor(s)
kern  :info  : [  217.930454] dump_intel_ipu_data: Found 2 supported PMIC(s)
```
I'll try to fix this later...

The other data should be okay.
